/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.karatetrophy.jooq.tables.AgeRange;
import org.karatetrophy.jooq.tables.BeltRange;
import org.karatetrophy.jooq.tables.Challenge;
import org.karatetrophy.jooq.tables.Competition;
import org.karatetrophy.jooq.tables.CompetitonDay;
import org.karatetrophy.jooq.tables.Composition;
import org.karatetrophy.jooq.tables.Dojo;
import org.karatetrophy.jooq.tables.Federation;
import org.karatetrophy.jooq.tables.KarateMaster;
import org.karatetrophy.jooq.tables.Karateka;
import org.karatetrophy.jooq.tables.Partecipation;
import org.karatetrophy.jooq.tables.Referee;
import org.karatetrophy.jooq.tables.TenderCommittee;
import org.karatetrophy.jooq.tables.Tournament;
import org.karatetrophy.jooq.tables.WeightRange;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KarateTrophy extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy</code>
     */
    public static final KarateTrophy KARATE_TROPHY = new KarateTrophy();

    /**
     * The table <code>karate_trophy.age_range</code>.
     */
    public final AgeRange AGE_RANGE = AgeRange.AGE_RANGE;

    /**
     * The table <code>karate_trophy.belt_range</code>.
     */
    public final BeltRange BELT_RANGE = BeltRange.BELT_RANGE;

    /**
     * The table <code>karate_trophy.challenge</code>.
     */
    public final Challenge CHALLENGE = Challenge.CHALLENGE;

    /**
     * The table <code>karate_trophy.competition</code>.
     */
    public final Competition COMPETITION = Competition.COMPETITION;

    /**
     * The table <code>karate_trophy.competiton_day</code>.
     */
    public final CompetitonDay COMPETITON_DAY = CompetitonDay.COMPETITON_DAY;

    /**
     * The table <code>karate_trophy.composition</code>.
     */
    public final Composition COMPOSITION = Composition.COMPOSITION;

    /**
     * The table <code>karate_trophy.dojo</code>.
     */
    public final Dojo DOJO = Dojo.DOJO;

    /**
     * The table <code>karate_trophy.federation</code>.
     */
    public final Federation FEDERATION = Federation.FEDERATION;

    /**
     * The table <code>karate_trophy.karate_master</code>.
     */
    public final KarateMaster KARATE_MASTER = KarateMaster.KARATE_MASTER;

    /**
     * The table <code>karate_trophy.karateka</code>.
     */
    public final Karateka KARATEKA = Karateka.KARATEKA;

    /**
     * The table <code>karate_trophy.partecipation</code>.
     */
    public final Partecipation PARTECIPATION = Partecipation.PARTECIPATION;

    /**
     * The table <code>karate_trophy.referee</code>.
     */
    public final Referee REFEREE = Referee.REFEREE;

    /**
     * The table <code>karate_trophy.tender_committee</code>.
     */
    public final TenderCommittee TENDER_COMMITTEE = TenderCommittee.TENDER_COMMITTEE;

    /**
     * The table <code>karate_trophy.tournament</code>.
     */
    public final Tournament TOURNAMENT = Tournament.TOURNAMENT;

    /**
     * The table <code>karate_trophy.weight_range</code>.
     */
    public final WeightRange WEIGHT_RANGE = WeightRange.WEIGHT_RANGE;

    /**
     * No further instances allowed
     */
    private KarateTrophy() {
        super("karate_trophy", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AgeRange.AGE_RANGE,
            BeltRange.BELT_RANGE,
            Challenge.CHALLENGE,
            Competition.COMPETITION,
            CompetitonDay.COMPETITON_DAY,
            Composition.COMPOSITION,
            Dojo.DOJO,
            Federation.FEDERATION,
            KarateMaster.KARATE_MASTER,
            Karateka.KARATEKA,
            Partecipation.PARTECIPATION,
            Referee.REFEREE,
            TenderCommittee.TENDER_COMMITTEE,
            Tournament.TOURNAMENT,
            WeightRange.WEIGHT_RANGE
        );
    }
}
