/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq;


import org.karatetrophy.jooq.tables.AgeRange;
import org.karatetrophy.jooq.tables.BeltRange;
import org.karatetrophy.jooq.tables.Challenge;
import org.karatetrophy.jooq.tables.Competition;
import org.karatetrophy.jooq.tables.CompetitonDay;
import org.karatetrophy.jooq.tables.Composition;
import org.karatetrophy.jooq.tables.Dojo;
import org.karatetrophy.jooq.tables.Federation;
import org.karatetrophy.jooq.tables.KarateMaster;
import org.karatetrophy.jooq.tables.Karateka;
import org.karatetrophy.jooq.tables.Partecipation;
import org.karatetrophy.jooq.tables.Referee;
import org.karatetrophy.jooq.tables.TenderCommittee;
import org.karatetrophy.jooq.tables.Tournament;
import org.karatetrophy.jooq.tables.WeightRange;


/**
 * Convenience access to all tables in karate_trophy.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>karate_trophy.age_range</code>.
     */
    public static final AgeRange AGE_RANGE = AgeRange.AGE_RANGE;

    /**
     * The table <code>karate_trophy.belt_range</code>.
     */
    public static final BeltRange BELT_RANGE = BeltRange.BELT_RANGE;

    /**
     * The table <code>karate_trophy.challenge</code>.
     */
    public static final Challenge CHALLENGE = Challenge.CHALLENGE;

    /**
     * The table <code>karate_trophy.competition</code>.
     */
    public static final Competition COMPETITION = Competition.COMPETITION;

    /**
     * The table <code>karate_trophy.competiton_day</code>.
     */
    public static final CompetitonDay COMPETITON_DAY = CompetitonDay.COMPETITON_DAY;

    /**
     * The table <code>karate_trophy.composition</code>.
     */
    public static final Composition COMPOSITION = Composition.COMPOSITION;

    /**
     * The table <code>karate_trophy.dojo</code>.
     */
    public static final Dojo DOJO = Dojo.DOJO;

    /**
     * The table <code>karate_trophy.federation</code>.
     */
    public static final Federation FEDERATION = Federation.FEDERATION;

    /**
     * The table <code>karate_trophy.karate_master</code>.
     */
    public static final KarateMaster KARATE_MASTER = KarateMaster.KARATE_MASTER;

    /**
     * The table <code>karate_trophy.karateka</code>.
     */
    public static final Karateka KARATEKA = Karateka.KARATEKA;

    /**
     * The table <code>karate_trophy.partecipation</code>.
     */
    public static final Partecipation PARTECIPATION = Partecipation.PARTECIPATION;

    /**
     * The table <code>karate_trophy.referee</code>.
     */
    public static final Referee REFEREE = Referee.REFEREE;

    /**
     * The table <code>karate_trophy.tender_committee</code>.
     */
    public static final TenderCommittee TENDER_COMMITTEE = TenderCommittee.TENDER_COMMITTEE;

    /**
     * The table <code>karate_trophy.tournament</code>.
     */
    public static final Tournament TOURNAMENT = Tournament.TOURNAMENT;

    /**
     * The table <code>karate_trophy.weight_range</code>.
     */
    public static final WeightRange WEIGHT_RANGE = WeightRange.WEIGHT_RANGE;
}
