/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BeltRange extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.belt_range</code>
     */
    public static final BeltRange BELT_RANGE = new BeltRange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.belt_range.Min_level</code>.
     */
    public final TableField<Record, String> MIN_LEVEL = createField(DSL.name("Min_level"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.belt_range.Max_level</code>.
     */
    public final TableField<Record, String> MAX_LEVEL = createField(DSL.name("Max_level"), SQLDataType.CHAR(50).nullable(false), this, "");

    private BeltRange(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private BeltRange(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.belt_range</code> table reference
     */
    public BeltRange(String alias) {
        this(DSL.name(alias), BELT_RANGE);
    }

    /**
     * Create an aliased <code>karate_trophy.belt_range</code> table reference
     */
    public BeltRange(Name alias) {
        this(alias, BELT_RANGE);
    }

    /**
     * Create a <code>karate_trophy.belt_range</code> table reference
     */
    public BeltRange() {
        this(DSL.name("belt_range"), null);
    }

    public <O extends Record> BeltRange(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, BELT_RANGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_BELT_RANGE_PRIMARY;
    }

    @Override
    public BeltRange as(String alias) {
        return new BeltRange(DSL.name(alias), this);
    }

    @Override
    public BeltRange as(Name alias) {
        return new BeltRange(alias, this);
    }

    @Override
    public BeltRange as(Table<?> alias) {
        return new BeltRange(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BeltRange rename(String name) {
        return new BeltRange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BeltRange rename(Name name) {
        return new BeltRange(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BeltRange rename(Table<?> name) {
        return new BeltRange(name.getQualifiedName(), null);
    }
}
