/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dojo extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.dojo</code>
     */
    public static final Dojo DOJO = new Dojo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.dojo.Address</code>.
     */
    public final TableField<Record, String> ADDRESS = createField(DSL.name("Address"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.dojo.Name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("Name"), SQLDataType.CHAR(50).nullable(false), this, "");

    private Dojo(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Dojo(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.dojo</code> table reference
     */
    public Dojo(String alias) {
        this(DSL.name(alias), DOJO);
    }

    /**
     * Create an aliased <code>karate_trophy.dojo</code> table reference
     */
    public Dojo(Name alias) {
        this(alias, DOJO);
    }

    /**
     * Create a <code>karate_trophy.dojo</code> table reference
     */
    public Dojo() {
        this(DSL.name("dojo"), null);
    }

    public <O extends Record> Dojo(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, DOJO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DOJO_PRIMARY;
    }

    @Override
    public Dojo as(String alias) {
        return new Dojo(DSL.name(alias), this);
    }

    @Override
    public Dojo as(Name alias) {
        return new Dojo(alias, this);
    }

    @Override
    public Dojo as(Table<?> alias) {
        return new Dojo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dojo rename(String name) {
        return new Dojo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dojo rename(Name name) {
        return new Dojo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dojo rename(Table<?> name) {
        return new Dojo(name.getQualifiedName(), null);
    }
}
