/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Karateka extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.karateka</code>
     */
    public static final Karateka KARATEKA = new Karateka();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.karateka.Gender</code>.
     */
    public final TableField<Record, String> GENDER = createField(DSL.name("Gender"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Surname</code>.
     */
    public final TableField<Record, String> SURNAME = createField(DSL.name("Surname"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Date_of_birth</code>.
     */
    public final TableField<Record, LocalDate> DATE_OF_BIRTH = createField(DSL.name("Date_of_birth"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("Name"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Fiscal_Code</code>.
     */
    public final TableField<Record, String> FISCAL_CODE = createField(DSL.name("Fiscal_Code"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Age</code>.
     */
    public final TableField<Record, Integer> AGE = createField(DSL.name("Age"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Weight</code>.
     */
    public final TableField<Record, Integer> WEIGHT = createField(DSL.name("Weight"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Dan_acquired</code>.
     */
    public final TableField<Record, Integer> DAN_ACQUIRED = createField(DSL.name("Dan_acquired"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>karate_trophy.karateka.Belt_color</code>.
     */
    public final TableField<Record, String> BELT_COLOR = createField(DSL.name("Belt_color"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.karateka.Karate_Master</code>.
     */
    public final TableField<Record, String> KARATE_MASTER = createField(DSL.name("Karate_Master"), SQLDataType.CHAR(50).nullable(false), this, "");

    private Karateka(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Karateka(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.karateka</code> table reference
     */
    public Karateka(String alias) {
        this(DSL.name(alias), KARATEKA);
    }

    /**
     * Create an aliased <code>karate_trophy.karateka</code> table reference
     */
    public Karateka(Name alias) {
        this(alias, KARATEKA);
    }

    /**
     * Create a <code>karate_trophy.karateka</code> table reference
     */
    public Karateka() {
        this(DSL.name("karateka"), null);
    }

    public <O extends Record> Karateka(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, KARATEKA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_KARATEKA_PRIMARY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.FKRECRUITMENT);
    }

    private transient KarateMaster _karateMaster;

    /**
     * Get the implicit join path to the
     * <code>karate_trophy.karate_master</code> table.
     */
    public KarateMaster karateMaster() {
        if (_karateMaster == null)
            _karateMaster = new KarateMaster(this, Keys.FKRECRUITMENT);

        return _karateMaster;
    }

    @Override
    public Karateka as(String alias) {
        return new Karateka(DSL.name(alias), this);
    }

    @Override
    public Karateka as(Name alias) {
        return new Karateka(alias, this);
    }

    @Override
    public Karateka as(Table<?> alias) {
        return new Karateka(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Karateka rename(String name) {
        return new Karateka(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Karateka rename(Name name) {
        return new Karateka(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Karateka rename(Table<?> name) {
        return new Karateka(name.getQualifiedName(), null);
    }
}
