/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Referee extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.referee</code>
     */
    public static final Referee REFEREE = new Referee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.referee.Gender</code>.
     */
    public final TableField<Record, String> GENDER = createField(DSL.name("Gender"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.referee.Surname</code>.
     */
    public final TableField<Record, String> SURNAME = createField(DSL.name("Surname"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.referee.Date_of_birth</code>.
     */
    public final TableField<Record, LocalDate> DATE_OF_BIRTH = createField(DSL.name("Date_of_birth"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.referee.Name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("Name"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.referee.Fiscal_Code</code>.
     */
    public final TableField<Record, String> FISCAL_CODE = createField(DSL.name("Fiscal_Code"), SQLDataType.CHAR(50).nullable(false), this, "");

    private Referee(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Referee(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.referee</code> table reference
     */
    public Referee(String alias) {
        this(DSL.name(alias), REFEREE);
    }

    /**
     * Create an aliased <code>karate_trophy.referee</code> table reference
     */
    public Referee(Name alias) {
        this(alias, REFEREE);
    }

    /**
     * Create a <code>karate_trophy.referee</code> table reference
     */
    public Referee() {
        this(DSL.name("referee"), null);
    }

    public <O extends Record> Referee(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, REFEREE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_REFEREE_PRIMARY;
    }

    @Override
    public Referee as(String alias) {
        return new Referee(DSL.name(alias), this);
    }

    @Override
    public Referee as(Name alias) {
        return new Referee(alias, this);
    }

    @Override
    public Referee as(Table<?> alias) {
        return new Referee(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Referee rename(String name) {
        return new Referee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Referee rename(Name name) {
        return new Referee(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Referee rename(Table<?> name) {
        return new Referee(name.getQualifiedName(), null);
    }
}
