/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TenderCommittee extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.tender_committee</code>
     */
    public static final TenderCommittee TENDER_COMMITTEE = new TenderCommittee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.tender_committee.ID_Committee</code>.
     */
    public final TableField<Record, String> ID_COMMITTEE = createField(DSL.name("ID_Committee"), SQLDataType.CHAR(50).nullable(false), this, "");

    private TenderCommittee(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TenderCommittee(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.tender_committee</code> table
     * reference
     */
    public TenderCommittee(String alias) {
        this(DSL.name(alias), TENDER_COMMITTEE);
    }

    /**
     * Create an aliased <code>karate_trophy.tender_committee</code> table
     * reference
     */
    public TenderCommittee(Name alias) {
        this(alias, TENDER_COMMITTEE);
    }

    /**
     * Create a <code>karate_trophy.tender_committee</code> table reference
     */
    public TenderCommittee() {
        this(DSL.name("tender_committee"), null);
    }

    public <O extends Record> TenderCommittee(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TENDER_COMMITTEE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_TENDER_COMMITTEE_PRIMARY;
    }

    @Override
    public TenderCommittee as(String alias) {
        return new TenderCommittee(DSL.name(alias), this);
    }

    @Override
    public TenderCommittee as(Name alias) {
        return new TenderCommittee(alias, this);
    }

    @Override
    public TenderCommittee as(Table<?> alias) {
        return new TenderCommittee(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TenderCommittee rename(String name) {
        return new TenderCommittee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TenderCommittee rename(Name name) {
        return new TenderCommittee(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TenderCommittee rename(Table<?> name) {
        return new TenderCommittee(name.getQualifiedName(), null);
    }
}
