/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tournament extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.tournament</code>
     */
    public static final Tournament TOURNAMENT = new Tournament();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.tournament.Start_date</code>.
     */
    public final TableField<Record, LocalDate> START_DATE = createField(DSL.name("Start_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.End_Date</code>.
     */
    public final TableField<Record, LocalDate> END_DATE = createField(DSL.name("End_Date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.Importance</code>.
     */
    public final TableField<Record, String> IMPORTANCE = createField(DSL.name("Importance"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.City</code>.
     */
    public final TableField<Record, String> CITY = createField(DSL.name("City"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.Name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("Name"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.Federation_Name</code>.
     */
    public final TableField<Record, String> FEDERATION_NAME = createField(DSL.name("Federation_Name"), SQLDataType.CHAR(50).nullable(false), this, "");

    /**
     * The column <code>karate_trophy.tournament.Winner</code>.
     */
    public final TableField<Record, Integer> WINNER = createField(DSL.name("Winner"), SQLDataType.INTEGER.nullable(false), this, "");

    private Tournament(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Tournament(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.tournament</code> table reference
     */
    public Tournament(String alias) {
        this(DSL.name(alias), TOURNAMENT);
    }

    /**
     * Create an aliased <code>karate_trophy.tournament</code> table reference
     */
    public Tournament(Name alias) {
        this(alias, TOURNAMENT);
    }

    /**
     * Create a <code>karate_trophy.tournament</code> table reference
     */
    public Tournament() {
        this(DSL.name("tournament"), null);
    }

    public <O extends Record> Tournament(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TOURNAMENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_TOURNAMENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.FKORGANIZATION);
    }

    private transient Federation _federation;

    /**
     * Get the implicit join path to the <code>karate_trophy.federation</code>
     * table.
     */
    public Federation federation() {
        if (_federation == null)
            _federation = new Federation(this, Keys.FKORGANIZATION);

        return _federation;
    }

    @Override
    public Tournament as(String alias) {
        return new Tournament(DSL.name(alias), this);
    }

    @Override
    public Tournament as(Name alias) {
        return new Tournament(alias, this);
    }

    @Override
    public Tournament as(Table<?> alias) {
        return new Tournament(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tournament rename(String name) {
        return new Tournament(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tournament rename(Name name) {
        return new Tournament(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tournament rename(Table<?> name) {
        return new Tournament(name.getQualifiedName(), null);
    }
}
