/*
 * This file is generated by jOOQ.
 */
package org.karatetrophy.jooq.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.karatetrophy.jooq.KarateTrophy;
import org.karatetrophy.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeightRange extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>karate_trophy.weight_range</code>
     */
    public static final WeightRange WEIGHT_RANGE = new WeightRange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>karate_trophy.weight_range.Min_weight</code>.
     */
    public final TableField<Record, Integer> MIN_WEIGHT = createField(DSL.name("Min_weight"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>karate_trophy.weight_range.Max_weight</code>.
     */
    public final TableField<Record, Integer> MAX_WEIGHT = createField(DSL.name("Max_weight"), SQLDataType.INTEGER.nullable(false), this, "");

    private WeightRange(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private WeightRange(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>karate_trophy.weight_range</code> table reference
     */
    public WeightRange(String alias) {
        this(DSL.name(alias), WEIGHT_RANGE);
    }

    /**
     * Create an aliased <code>karate_trophy.weight_range</code> table reference
     */
    public WeightRange(Name alias) {
        this(alias, WEIGHT_RANGE);
    }

    /**
     * Create a <code>karate_trophy.weight_range</code> table reference
     */
    public WeightRange() {
        this(DSL.name("weight_range"), null);
    }

    public <O extends Record> WeightRange(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, WEIGHT_RANGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KarateTrophy.KARATE_TROPHY;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_WEIGHT_RANGE_PRIMARY;
    }

    @Override
    public WeightRange as(String alias) {
        return new WeightRange(DSL.name(alias), this);
    }

    @Override
    public WeightRange as(Name alias) {
        return new WeightRange(alias, this);
    }

    @Override
    public WeightRange as(Table<?> alias) {
        return new WeightRange(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WeightRange rename(String name) {
        return new WeightRange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WeightRange rename(Name name) {
        return new WeightRange(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WeightRange rename(Table<?> name) {
        return new WeightRange(name.getQualifiedName(), null);
    }
}
